# Generated by Django 4.2.11 on 2024-05-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milo'), ('VM', 'Vinamilk'), ('DL', 'Dalat Milk'), ('DT', 'Dutch Lady'), ('BV', 'Ba Vì'), ('SH', 'Sữa Hạt'), ('YK', 'Yakult'), ('FM', 'Fami'), ('TH', 'TH True Milk'), ('NF', 'Nutifood')], max_length=2),
        ),
    ]
